[package]
name = "CS205_C_CPP_2020Spring_RUST_lab07"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab07_01"
path = "lab07_01.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab07_02"
path = "lab07_02.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab07_03"
path = "lab07_03.rs"
test = true

# rusrc means rust-src
[dependencies]