[package]
name = "CS205_C_CPP_2020Spring_RUST_lab06"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab06_01"
path = "lab06_01.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab06_02"
path = "lab06_02.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab06_03"
path = "lab06_03.rs"
test = true

# rusrc means rust-src
[dependencies]
libc = "0.2.97"