[package]
name = "CS205_C_CPP_2020Spring_RUST_lab02"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab02_01"
path = "lab02_01.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab02_02"
path = "lab02_02.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab02_03"
path = "lab02_03.rs"
test = false

[[test]]
name = "CS205_C_CPP_2020Spring_RUST_lab02_02_test"
path = "lab02_02_test.rs"

# rusrc means rust-src
[dependencies]
