// SPDX-License-Identifier: AGPL-3.0-or-later
/*
CS203_DSAA_template

Copyright (C) 2022  nanoseeds

*/

#ifndef CS203_DSAA_TEMPLATE_BASIC_INSTALL_PACKAGES_LIB2_LIB2_HPP
#define CS203_DSAA_TEMPLATE_BASIC_INSTALL_PACKAGES_LIB2_LIB2_HPP

#include <cstdint>

int32_t function2();

#endif //CS203_DSAA_TEMPLATE_BASIC_INSTALL_PACKAGES_LIB2_LIB2_HPP
