[package]
name = "CS205_C_CPP_2020Spring_RUST_Ass04"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_ass4_01"
path = "ass4_01.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_ass4_02"
path = "ass4_02.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_ass4_03"
path = "ass4_03.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_ass4_04"
path = "ass4_04.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_ass4_05"
path = "ass4_05.rs"
test = false

[dependencies]
rand = "0.8.4"
csv = "1.1"
[build-dependencies]
