function(Add_Sub_Dir_List _List PrePath PostPath)
    foreach (element IN LISTS ${_List})
        add_subdirectory(${PrePath}${element}${PostPath})
    endforeach ()
endfunction()

function(MENTION_YEAR)
    set(MAIN_CUSTOM_SEMESTER 2020-SPRING)
    set(FOLLOW_CUSTOM_SEMESTER 2021-SPRING)
    MESSAGE(STATUS "THIS PROJECT WRITE FOR ${MAIN_CUSTOM_SEMESTER}")
    MESSAGE(STATUS "THIS PROJECT ALSO AVAILABLE FOR ${FOLLOW_CUSTOM_SEMESTER}")
endfunction()
MENTION_YEAR()