[package]
name = "CS205_C_CPP_2020Spring_RUST_lab01"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab01_hello"
path = "hello.rs"
test = false
doctest = false
bench = false
doc = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab01_smile"
path = "smile.rs"
test = false
doctest = false
bench = false
doc = false

# rusrc means rust-src
[dependencies]
