[package]
name = "CS205_C_CPP_2020Spring_RUST_lab13"
version = "0.0.1"
authors = ["Certseeds <Certseeds <51754303+Certseeds@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab13_01"
path = "lab13_01.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab13_02"
path = "lab13_02.rs"
test = false

[[bin]]
name = "CS205_C_CPP_2020Spring_RUST_lab13_04"
path = "lab13_04.rs"
test = false

# rusrc means rust-src
[dependencies]