# @Github: https://github.com/Certseeds/CS203_DSAA_template
# @Organization: SUSTech
# @Author: nanoseeds
# @Date: 2020-07-26 16:36:10
# @LastEditors: nanoseeds
#@LastEditTime: 2020-07-26 16:43:03
# This is a basic workflow to help you get started with Actions

name: test for pull_request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ dev ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test for pull_request
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest,windows-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      # ensure the path and files of project
      - name: ensure the path and files of project
        run: sudo apt install tree; tree
        if: ${{matrix.os != 'windows-latest'}}

      - name: Use cmake
        run: cmake --version

      - name: prepare folder
        run: cmake -E make_directory ./CMAKE_DEBUG_PATH

      - name: cmake prepare for compile
        working-directory: ./CMAKE_DEBUG_PATH
        run: cmake .. -DCMAKE_BUILD_TYPE=DEBUG

      - name: cmake compile
        working-directory: ./CMAKE_DEBUG_PATH
        run: cmake --build . --config DEBUG --parallel

      - name: cmake test
        working-directory: ./CMAKE_DEBUG_PATH
        run: ctest  --parallel $(nproc)
        if: ${{matrix.os != 'windows-latest'}}

      - name: tree
        run: tree

  # This workflow contains a single job called "build"
  build:
    name: test for the release script
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      # ensure the path and files of project
      - name: ensure the path and files of project
        run: sudo apt install tree; tree

      - name: run script
        working-directory: ./script
        run: python3 file_template.py

      - name: tree the packet
        run: tree

